name: Check Quality

on: pull_request

env:
  NODE_VERSION: 16.14.2
  NODE_OPTIONS: --max_old_space_size=8192

jobs:
  lint:
    name: Lint files
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install NPM deps
        run: npm ci
      - name: Run linting
        run: npm run lint

  unit-test:
    name: Unit Test
    environment: development
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install NPM deps
        run: npm ci
      - name: Run unit tests
        run: npm run jest